E_police_Station/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ep_app.urls'))

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ep_app/urls.py
from os import name
from django.urls import path
from . import views

urlpatterns = [

    path('',views.index,name='index'),
    path("add_missing_persons/",views.add_missing_persons,name = 'add_missing_persons'),
    path('Missing_PersonsListView/',views.Missing_PersonsListView.as_view(),name = 'Missing_PersonsListView'),
    path('Rules_RegulationsCreateView/',views.Rules_RegulationsCreateView.as_view(),name='Rules_RegulationsCreateView'),
    path('Rules_RegulationsListView/',views.Rules_RegulationsListView.as_view(),name = 'Rules_RegulationsListView'),
    path("Emergency_Information/",views.Emergency_Information,name="Emergency_Information"),
    path("Show_emergency/",views.Show_emergencyListView.as_view(),name = 'Show_emergency'),
#-----------------------------------------------------------------------------------------------------------#
    
    path('registration/', views.registration,name='registration'),
    path('otp_verify/',views.otp_verify, name = 'otp_verify'),
    path('citizen_login/',views.citizen_login,name='citizen_login'),
    path('citizen_logout/',views.citizen_logout,name='citizen_logout'),
    path('citizen_profile/',views.citizen_profile, name='citizen_profile'),
    path('view_citizen/',views.view_citizen,name='view_citizen'),
    path("update_citizen/<int:pk>",views.CitizenprofileUpdateView.as_view(),name="update_citizen"),
    path("citizen_password/",views.citizen_password,name = "citizen_password"),

    path("forgot_password/",views.forgot_password,name="forgot_password"),
    path("otp_password/",views.otp_password,name = "otp_password"),
    path("citinew_password/",views.citinew_password,name = "citinew_password"),
    
    path('file_fir/',views.file_fir,name='file_fir'),
    path('file_complain/',views.file_complain,name='file_complain'),
    path("fir_details/",views.fir_details,name = 'fir_details'),
    path("complain_details/",views.complain_details, name = "complain_details"),
    path('police_station/',views.police_station,name='police_station'),
    path('search_police_station/',views.search_police_station, name = 'search_police_station'),
    path('feedback/',views.feedback,name = 'feedback'),

#-------------------------------------------------------------------------------------------------------#

    path("login_details/",views.login_details,name ="login_details"),
    path("inspector_login/",views.inspector_login,name="inspector_login"),
    path("inspector_otp/",views.inspector_otp,name = "inspector_otp"),
    path("inspector_index/",views.inspector_index,name = "inspector_index"),
    path("inspector_logout/",views.inspector_logout,name = "inspector_logout"),
    path("inspector/",views.inspector,name = "inspector"),
    path("view_inspector/",views.view_inspector,name = 'view_inspector'),

    path("inspector_password/",views.inspector_password,name = "inspector_password"),
    path("update_inspector/<int:pk>",views.InspectorUpdateView.as_view(),name='update_inspector'),

    path("inspector_forgot/",views.inspector_forgot,name = 'inspector_forgot'),
    path("forgot_otp/",views.forgot_otp,name = "forgot_otp"),
    path("inspecnew_password/",views.inspecnew_password,name="inspecnew_password"),

#------------------------------------------------------------------------------------------------------#
    path("police_index/",views.police_index,name="police_index"),
    path("commissioner_login_details/",views.commissioner_login_details,name = "commissioner_login_details"),
    path("commissioner_login/",views.commissioner_login,name="commissioner_login"),
    path("commissioner_otp/",views.commissioner_otp,name="commissioner_otp"),
    path("commissioner_logout/",views.commissioner_logout,name="commissioner_logout"),
    path("commissioner/",views.commissioner,name='commissioner'),
    path("commissioner_view/",views.commissioner_view,name="commissioner_view"),
    path("commissioner_password/",views.commissioner_password,name='commissioner_password'),
    path("commissioner_update/<int:pk>/",views.commissioner_UpdateView.as_view(),name='commissioner_update'),

    path("commissioner_forgot/",views.commissioner_forgot,name="commissioner_forgot"),
    path("commissioner_forgot_otp/",views.commissioner_forgot_otp,name = "commissioner_forgot_otp"),
    path("commissionernew_password/",views.commissionernew_password,name="commissionernew_password"),

    path("manage_police_station/",views.manage_police_station,name="manage_police_station"),
    path("update_police_station/<int:pk>/",views.police_stationUpdateView.as_view(),name="update_police_station"),
    path("delete_police_station/<int:pk>/",views.police_stationDeleteView.as_view(),name ="delete_police_station"),

    path("manage_inspector/",views.manage_inspector,name='manage_inspector'),
    path("update_login_inspector/<int:pk>/",views.Inspector_loginUpdateview.as_view(),name="update_login_inspector"),
    path("Delete_login_inspector/<int:pk>",views.Inspector_loginDeleteView.as_view(),name = "Delete_login_inspector"),
    path("Details_inspector/<int:id>/",views.Details_inspector,name="Details_inspector"),

    path("manage_constable/",views.manage_constable,name = 'manage_constable'),
    path("update_constable/<int:pk>",views.constable_UpdateView.as_view(),name="update_constable"),
    path("delete_constable/<int:pk>",views.constable_DeleteView.as_view(),name = "delete_constable"),

    path("fir_details_view/",views.fir_details_view,name="fir_details_view"),
    path("complain_details_view/",views.complain_details_view,name="complain_details_view"),


    path("sub_inspector/",views.sub_inspector,name = "sub_inspector"),
    path("constable/",views.constable,name="constable"),
    path("service_officers/",views.service_officers,name = "service_officers"),


    path("view_fir/",views.view_fir, name = "view_fir"),
    path("view_complain/",views.view_complain, name = "view_complain"),
    path("manage_fir/",views.manage_fir, name="manage_fir"),
    path("manage_complain/",views.manage_complain, name="manage_complain"),
    path("fir_status/<int:pk>",views.FirUpdateView.as_view(),name="fir_status"),
    path("complain_status/<int:pk>/",views.ComplainUpdateView.as_view(),name="complain_status"),
    path("user_details/",views.user_details,name="user_details"),
 

#-------------------------------------------------------------------------------------------------------#

    path("crime_category/",views.crime_category,name = "crime_category"),
    path("crime_sub_category/",views.crime_sub_category,name = "crime_sub_category"),
    path("load_crime_sub_category/", views.load_crime_sub_category, name='load_crime_sub_category'), # AJAX

    path("city/",views.city, name= "city"),
    path("taluka/",views.taluka, name ="taluka"),
    path("village/",views.village, name = "village"),
    path("load_taluka/", views.load_taluka, name='load_taluka'), # AJAX
    path("load_village/",views.load_village,name = "load_village"), #AJAX

]

ep_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class  Citizenprofile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pic')
    GENDER_CHOICES = (('M', 'Male'),('F', 'Female'))
    mobile_no = models.IntegerField()
    phone_no = models.IntegerField()
    dob = models.DateField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address = models.TextField()
    City = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    pincode = models.IntegerField()

    def __str__(self):
        return self.user.username

class City(models.Model):
    city = models.CharField(max_length=256)

    def __str__(self):
        return self.city
    
class Taluka(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, blank=True)
    taluka = models.CharField(max_length=256)

    def __str__(self):
        return self.taluka

class Village(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, blank=True)
    taluka = models.ForeignKey(Taluka, on_delete=models.CASCADE, null=True, blank=True)
    village = models.CharField(max_length=256)

    def __str__(self):
        return self.village

class Crime_Category(models.Model):
    crime_category = models.CharField(max_length=256)

    def __str__(self):
        return self.crime_category

class Crime_Sub_Category(models.Model):
    crime_category = models.ForeignKey(Crime_Category, on_delete=models.CASCADE)
    crime_sub_category = models.CharField(max_length=256)
    description = models.TextField()

    def __str__(self):
        return self.crime_sub_category

class Police_Station(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=True, blank=True)
    taluka = models.ForeignKey(Taluka, on_delete=models.CASCADE, null=True, blank=True)
    village = models.ForeignKey(Village, on_delete=models.CASCADE, null=True, blank=True)
    Police_station_name = models.CharField(max_length=200)
    address = models.TextField(max_length=200)
    phone_no = models.IntegerField(null=True, blank=True)
    mobile_no = models.IntegerField(null=True, blank=True)
    email_address = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.Police_station_name

    def get_absolute_url(self):
        return reverse('manage_police_station')

class Fir(models.Model):
    Satus_choices = (('Activate','Activate'),('Inprocess', 'Inprocess'),('Closed','Closed'))
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    police_station = models.ForeignKey(Police_Station, on_delete=models.CASCADE, null=True, blank=True)
    crime_category = models.ForeignKey(Crime_Category, on_delete=models.CASCADE, null=True , blank=True)
    crime_sub_category = models.ForeignKey(Crime_Sub_Category, on_delete=models.CASCADE, null=True , blank=True)
    incident_place = models.TextField()
    Date_and_Time = models.DateTimeField()
    Crime_Description = models.TextField()
    Fir_againts = models.TextField()
    proof = models.FileField(upload_to='proof', null=True , blank=True)
    status = models.CharField(max_length=20, choices=Satus_choices)
    Reason = models.CharField(max_length=256)
    FIR_Date_and_Time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.username.username

    def get_absolute_url(self):
        return reverse('view_fir')

class Complain(models.Model):
    Satus_choices = (('Activate','Activate'),('Inprocess', 'Inprocess'),('Closed','Closed'))
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    police_station = models.ForeignKey(Police_Station, on_delete=models.CASCADE, null=True, blank=True)
    incident_place = models.TextField()
    Date_and_Time = models.DateTimeField( null=True,blank=True)
    Crime_Description = models.TextField()
    complain_againts = models.TextField()
    proof = models.FileField(upload_to='proof', null=True, blank=True)
    status = models.CharField(max_length=20, choices=Satus_choices)
    Reason = models.CharField(max_length=256)
    complain_Date_and_Time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.username.username

    def get_absolute_url(self):
        return reverse('view_complain')

class Feedback(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    Feedback = models.TextField()
    Photo = models.ImageField(upload_to = "photos_videos/", max_length=500 , null=True, blank=True)
    Video = models.FileField(upload_to="photos_videos/", max_length=500, null=True, blank=True)

    def __str__(self):
        return self.username.username


class Inspector_login(models.Model):
    username = models.CharField(max_length=256, unique=True)
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    email = models.EmailField()
    password = models.CharField(max_length = 20 , null=True,blank=True)

    def __str__(self):
        return self.username

class Inspector(models.Model):
    GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))
    user = models.OneToOneField(Inspector_login, on_delete=models.CASCADE)
    police_station = models.ForeignKey(Police_Station, on_delete=models.CASCADE, null=True, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pic')
    Age = models.IntegerField()
    date_of_birth = models.DateField()
    mobile_no = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address = models.TextField()
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    pincode = models.IntegerField()

    def __str__(self):
        return self.user.username

class Sub_Inspector(models.Model):
    GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))
    username = models.CharField(max_length=200, unique=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    profile_pic = models.ImageField(upload_to='profile_pic')
    date_of_birth = models.DateField()
    mobile_no = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address = models.TextField()
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    pincode = models.IntegerField()

    def __str__(self):
        return self.username

class Constable(models.Model):
    GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))
    username = models.CharField(max_length=200, unique=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField()
    profile_pic = models.ImageField(upload_to='profile_pic')
    date_of_birth = models.DateField()
    mobile_no = models.IntegerField()
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    address = models.TextField()
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    pincode = models.IntegerField()

    def __str__(self):
        return self.username

class Service_Officers(models.Model):
    police_station = models.OneToOneField(Police_Station, on_delete=models.CASCADE)
    inspector = models.OneToOneField(Inspector_login, on_delete=models.CASCADE)
    sub_inspector = models.OneToOneField(Sub_Inspector, on_delete=models.CASCADE)
    constable = models.OneToOneField(Constable, on_delete=models.CASCADE)

    def __str__(self):
        return self.police_station.Police_station_name

class Missing_Persons(models.Model):
    Full_Name = models.CharField(max_length=256)
    Photo = models.ImageField(upload_to= 'missing_persons')
    Date_of_birth = models.DateField()
    Age = models.IntegerField()
    Nickname = models.CharField(max_length=256,blank=True,null=True)
    weight = models.IntegerField()
    height = models.CharField(max_length=10)
    Skin_color = models.CharField(max_length=256)
    Missing_Date = models.DateField()
    Address = models.TextField()
    Contact_no = models.BigIntegerField()

    def __str__(self):
        return self.Full_Name

class Rules_Regulations(models.Model):
    Title = models.CharField(max_length=256)
    Document = models.FileField(upload_to='rules_regulation')

    def __str__(self):
        return self.Title

    def get_absolute_url(self):
        return reverse('index')

class Commissioner_login(models.Model):
    username = models.CharField(max_length=256, unique=True)
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)
    email = models.EmailField()
    password = models.CharField(max_length = 20 , null=True,blank=True)

    def __str__(self):
        return self.username

class Commissioner(models.Model):
    GENDER_CHOICES = (('Male', 'Male'), ('Female', 'Female'))
    user = models.OneToOneField(Commissioner_login, on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pic')
    Age = models.IntegerField()
    date_of_birth = models.DateField()
    mobile_no = models.IntegerField()
    gender = models.CharField(max_length=7, choices=GENDER_CHOICES)
    address = models.TextField()
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    pincode = models.IntegerField()

    def __str__(self):
        return self.user.username

class Emergency_Information(models.Model):
    Name = models.CharField(max_length=200)
    Number = models.BigIntegerField()

templates/services/ajax.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    
    $("#id_crime_category").change(function () {
        const url = $("#firform").attr("crime-sub-catgory-url"); 
        const crime_category_id = $(this).val();  

        $.ajax({                       
            url: url,                    
            data: {
                'crime_category_id': crime_category_id      
            },
            success: function (data) {   
                $("#id_crime_sub_category").html(data);  
                
            }
        });

    });

    $("#id_city").change(function () {
        const url = $("#searchform").attr("taluka-url"); 
        const city_id = $(this).val();  

        $.ajax({                       
            url: url,                    
            data: {
                'city_id': city_id      
            },
            success: function (data) {   
                $("#id_taluka").html(data);  
                
            }
        });

    });

    $("#id_taluka").change(function () {
        const url = $("#searchform").attr("village-url"); 
        const taluka_id = $(this).val();  

        $.ajax({                       
            url: url,                    
            data: {
                'taluka_id': taluka_id      
            },
            success: function (data) {   
                $("#id_village").html(data);  
                
            }
        });

    });
</script>

templates/services/complain_details.html
{% extends 'base.html' %}

{% block content %}

    
    <div class="container">
        
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Police Station</th>
                    <th>Incident Place</th>
                    <th>Date and Time</th>
                    <th>Crime Description</th>
                    <th>Complain Againts</th>
                    <th>Proof</th>
                    <th>Status</th>
                    <th>Reason</th>
                    <th>Complain Date and Time</th>
                </tr>
            </thead>
            <tbody>
                {% for object in complain_detail %}
                    {% if request.session.username == object.username.username%}
                        <tr>
                            <td>{{object.username.username}}</td>
                            <td>{{object.police_station}}</td>
                            <td>{{object.incident_place}}</td>
                            <td>{{object.Date_and_Time}}</td>
                            <td>{{object.Crime_Description}}</td>
                            <td>{{object.complain_againts}}</td>
                            <td>{{object.proof}}</td>
                            <td>{{object.status}}</td>
                            <td>{{object.Reason}}</td>
                            <td>{{object.complain_Date_and_Time}}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
        </table>
        
    </div>
    

{% endblock %}

templates/services/complain_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <center>
            <h1 class="btn btn-lg btn-primary">File Complain</h1>
            <hr>
            <form action="{% url 'file_complain' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{form.as_table}}
                </table>
                <input type="hidden" name="ps_name" value="{{ps}}">
                <input type="Submit" name="filecomplain" value="FILE Complain" class="btn btn-success">
            </form>
        </center>
    </div>
    
{% endblock %}

templates/services/fir_details.html
{% extends 'base.html' %}

{% block content %}

    
    <div class="container">
        
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Police Station</th>
                    <th>Crime Category</th>
                    <th>Crime Sub Category</th>
                    <th>Incident Place</th>
                    <th>Date and Time</th>
                    <th>Crime Description</th>
                    <th>Fir Againts</th>
                    <th>Proof</th>
                    <th>Status</th>
                    <th>Reason</th>
                    <th>FIR Date and Time</th>
                </tr>
            </thead>
            <tbody>
                
                {% for object in fir_detail %}
                {% if request.session.username == object.username.username%}
                <tr>
                    <td>{{object.username.username}}</td>
                    <td>{{object.police_station}}</td>
                    <td>{{object.crime_category}}</td>
                    <td>{{object.crime_sub_category}}</td>
                    <td>{{object.incident_place}}</td>
                    <td>{{object.Date_and_Time}}</td>
                    <td>{{object.Crime_Description}}</td>
                    <td>{{object.Fir_againts}}</td>
                    <td>{{object.proof}}</td>
                    <td>{{object.status}}</td>
                    <td>{{object.Reason}}</td>
                    <td>{{object.FIR_Date_and_Time}}</td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/services/fir_form.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="container">
        <center><h1>File FIR</h1>
            <hr>
            <form action="{% url 'file_fir' %}" method="POST" id="firform" crime-sub-catgory-url="{% url 'load_crime_sub_category' %}"enctype="multipart/form-data">
                {% csrf_token %}
                <table>
                    {{fir.as_table}}
                </table>
                <input type="hidden" name="ps_name" value="{{ps}}">
                <input type="Submit" name="filefir" value="FILE FIR" class="btn btn-success">
            </form>
        </center>
    </div>

{% include 'services/ajax.html' %}

{% endblock %}

    